spring.application.name=ms-asistencia
# coloco el puerto 8084 para no interferir en los puertos de mis compañeros y hacer pruebas en sql.
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/pb_asistencia_db?createDatabaseIfNotExist=true
spring.datasource.username=root
# Cambiar 'root' por tu contraseña real de MySQL en este PC
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect