server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: asistencia-service
          uri: lb://ms-asistencia
          predicates:
            - Path=/api/v1/asistencias/**

        - id: atletas-service
          uri: lb://ms-atletas
          predicates:
            - Path=/api/v1/atletas/**

        - id: ejercicios-service
          uri: lb://ms-ejercicios
          predicates:
            - Path=/api/v1/ejercicios/**

        - id: leaderboard-service
          uri: lb://ms-leaderboard
          predicates:
            - Path=/api/v1/leaderboard/**
      
        - id: marcas-service
          uri: lb://ms-marcas
          predicates:
            - Path=/api/v1/marcas/**
        
        - id: membresias-service
          uri: lb://ms-membresias
          predicates:
            - Path=/api/v1/membresias/**

        - id: rutinas-service
          uri: lb://ms-rutinas
          predicates:
            - Path=/api/v1/rutinas/**

        - id: verificaciones-service
          uri: lb://ms-verificaciones
          predicates:
            - Path=/api/v1/verificaciones/**
        
        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    "[org.springframework.cloud.gateway]": TRACE
    "[org.springframework.http.server.reactive]": DEBUG