server.port=8081
spring.application.name=ms-atletas

# Configuración MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_atletas?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Logs (Exigencia de la rúbrica)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
