# Puerto asignado para Membresias (8082 para no chocar con asistencia)
server.port=8082
spring.application.name=ms-membresia

# Conexión a la base de datos exclusiva de membresias
spring.datasource.url=jdbc:mysql://localhost:3306/pb_membresias_db?createDatabaseIfNotExist=true
spring.datasource.username=root
# Recuerda poner la contraseña de tu MySQL local
spring.datasource.password=root 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para crear la tabla automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
